### autostart.conf
### Commentary:
## Applications to be autostarted.
### Configuration:

exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id feh --bg-scale ../wallpapers/glowing-mushrooms.png
exec --no-startup-id polybar
exec --no-startup-id nm-applet
exec --no-startup-id /usr/sbin/xmodmap ~/.Xmodmap
