- name: "Check if Packer directory is empty"
  register: packerFilesFound
  ansible.builtin.stat:
    path: /home/{{ ansible_user_id }}/.local/share/nvim/site/pack/packer/start/packer.nvim

- name: "Clone Packer repository"
  when: packerFilesFound.stat.exists == false
  ansible.builtin.shell:
    cmd: git clone --depth 1 https://github.com/wbthomason/packer.nvim /home/{{ ansible_user_id }}/.local/share/nvim/site/pack/packer/start/packer.nvim

- name: "Check if Oh My Fish directory is empty"
  register: omfFilesFound
  ansible.builtin.stat:
    path: /home/{{ ansible_user_id }}/.local/share/omf

- name: "Perform Oh My Fish installation"
  when: omfFilesFound.stat.exists == false
  ansible.builtin.shell:
    cmd: fish (curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | psub) --noninteractive  --yes
