---
- hosts: main
  connection: local
  pre_tasks:
    - name: "Install Dependencies"
      become: true
      ansible.builtin.package:
        name:
          - alacritty
          - fish
          - lua
          - neovim
          - tmux
        state: latest
  roles:
    - symlink

